version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - unconvert

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
